### ISSUE TITLE
Error with pip install

### ISSUE THREAD

**Issue by dtalkachou** [Nicceboy/python-markdown-generator#1]
I have errors with correctly instalation this package from pip.

```
ModuleNotFoundError: No module named 'markdowngenerator.config'
```
I was install this package manually, but I want include this package to requirements.txt and users will have this problem.

**Comment by Nicceboy** [comment]
At first, I have to apologize for bit inactivity for this project. I haven't had personally time for this project right now.

Would you like to provide more steps how you are trying to install it? Package is not currently in pip, but I might add it into it, if there is a need.  That would make installation as dependecy easier.

**Comment by dtalkachou** [comment]
I tried to install this package wtih following command:
```
pip install git+https://...
```

My solution to resolve this problem - install with setup.py, but i give other error :(

**Comment by Nicceboy** [comment]
I took a look, and the `setup.py` is invalid if you would like to use `config` module. It is not included when installed as dependency. i can try to fix it in this week and do some other improvements.

**Comment by dtalkachou** [comment]
Yes, try fix it. I already migrate to other package, but you package have better syntax and I can use it in the future.
