### ISSUE TITLE
AttributeError: 'MarkdownGenerator' object has no attribute 'file'

### ISSUE THREAD

**Issue by theodore86** [Nicceboy/python-markdown-generator#4]
Hi,

Thank you for this great library,

It seems that the following exception is being raised whenever i use the context manager of the library:

```
File ~/libdoc-markdown/.tox/ipython/lib/python3.10/site-packages/markdowngenerator/markdowngenerator.py:232, in MarkdownGenerator.genTableOfContent(self, linenumber, max_depth)
    230 if self.enable_write:
    231     self.document.close()
--> 232     self.document = open(self.file, "w")
    233     self.document.writelines(self.document_data_array)

AttributeError: 'MarkdownGenerator' object has no attribute 'file'
```

Most probably is a mistypo: ``self.filename`` rather than ``self.file``

**Comment by Nicceboy** [comment]
Thanks for bringing this up.
I also noticed couple other issues while investigating this.
* ToC should be disabled if file is written dynamically, otherwise benefits are lost
* ToC should start from line 1 because it is hard to configure at the moment

I will fix these shortly.
