### ISSUE TITLE
Package requirements changed

### ISSUE THREAD

**Issue by theodore86** [Nicceboy/python-markdown-generator#5]
ERROR: Package 'python-markdown-generator' requires a different Python: 3.9.0 not in '>=3.10,<4.0'

This is intentional?

Thanks,
Theo

**Comment by Nicceboy** [comment]
I switched to new pyproject.toml format and poetry, and I might have put too strict requirements.
Thanks for noting. When I have time, I should put tests for different Python versions to verify it works.

I believe that it should work from 3.7 and up, however.

**Comment by theodore86** [comment]
No it doesn't, tried to install it at python3.9 and it fails with the message: ```ERROR: Package 'python-markdown-generator' requires a different Python: 3.9.0 not in '>=3.10,<4.0'```, works only for python3.10 and upwards

**Comment by theodore86** [comment]
After the [commit](https://github.com/Nicceboy/python-markdown-generator/commit/8b8801f39a34d053f53e3a2eb76a8553e6bee7eb) installation succeeded!

Thank you very much!
